let state = {
    // data: {
    //   titles: [
    //     { title: "Материал " },
    //     { title: "Толщина " },
    //     { title: "Длина " },
    //     { title: "Ширина " },
    //     { title: "Сторона " },
    //     { title: "Диаметр " },
    //     { title: "Угол " },
    //     { title: "Количество, шт." },
    //     { title: ", град." },
    //     { title: ", мм." },
    //     { title: "A" },
    //     { title: "B" },
    //     { title: "D" },
    //     { title: "d" },
    //     { title: "Расcчитать" },
    //     { title: "Добавить" },
    //     { title: "αᵒ" },
    //     { title: "h" },
    //     { title: "Заказать" },
    //     { title: "email" },
    //     { title: "tel" },
    //     { title: "Введите адрес e-mail" },
    //     { title: "Введите номер телефона" },
    //     { title: "Реквизиты" },
    //     { title: "Отправить" },
    //   ],
    //   steels: [
    //     { steel: "Сталь 3" },
    //     { steel: "Сталь 20" },
    //     { steel: "Сталь 45" },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],

    //   vid: {
    //     sel1: "sel1",
    //     sel2: "sel2",
    //     in1: "in1",
    //     in2: "in2",
    //     in3: "in3",
    //     in4: "in4",
    //   },
    //   form: {
    //     rec: "rec",
    //     tri: "tri",
    //     cir: "cir",
    //     was: "was",
    //     sec: "sec",
    //   },
    //   costBD: [
    //     [
    //       "Сталь 3",
    //       { s: 3, steelcost: 66, cutcost: 150 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 3",
    //       { s: 4, steelcost: 43, cutcost: 20 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 3",
    //       { s: 5, steelcost: 43, cutcost: 25 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 3",
    //       { s: 6, steelcost: 43, cutcost: 29 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 3",
    //       { s: 8, steelcost: 43, cutcost: 40 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 3",
    //       { s: 10, steelcost: 43, cutcost: 50 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 20",
    //       { s: 5, steelcost: 45, cutcost: 25 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 20",
    //       { s: 6, steelcost: 45, cutcost: 29 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 20",
    //       { s: 8, steelcost: 45, cutcost: 40 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 20",
    //       { s: 10, steelcost: 45, cutcost: 50 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 45",
    //       { s: 6, steelcost: 50, cutcost: 29 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 45",
    //       { s: 8, steelcost: 50, cutcost: 40 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //     [
    //       "Сталь 45",
    //       { s: 10, steelcost: 55, cutcost: 50 },
    //       {
    //         recholders: {
    //           param: { Amin: 10, Amax: 1000, Bmin: 10, Bmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         triholders: {
    //           param: {
    //             Amin: 10,
    //             Amax: 1000,
    //             Bmin: 10,
    //             Bmax: 1000,
    //             alphamin: 5,
    //             alphamax: 90,
    //           },
    //           ps1: "10-1000",
    //           ps2: "max 90",
    //           ps3: "0",
    //         },
    //         cirholders: {
    //           param: { Dmin: 10, Dmax: 1000 },
    //           ps1: "10-1000",
    //           ps2: "0",
    //         },
    //         washolders: {
    //           param: { Dmin: 20, Dmax: 1000, dmin: 10, dmax: 990 },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "0",
    //         },
    //         secholders: {
    //           param: {
    //             dmin: 10,
    //             dmax: 990,
    //             hmin: 5,
    //             hmax: 990,
    //             alphamin: 5,
    //             alphamax: 180,
    //           },
    //           ps1: "20-1000",
    //           ps2: "10-990",
    //           ps3: "max 180",
    //           ps4: "0",
    //         },
    //       },
    //     ],
    //   ],
    // },
    // rectangle: {
    //   newArray: {
    //     type: "",
    //     id: 1,
    //     steel: 1,
    //     param: {
    //       A: 1,
    //       B: 1,
    //     },
    //     s: 1,
    //     Q: 1,
    //     m: 0.5,
    //     summ_m: 0.5,
    //     S: 0.03,
    //     summ_S: 10,
    //     P: 0,
    //     cost: 1050,
    //     summ: 2100,
    //   },
    //   recholders: {
    //     ps1: "",
    //     ps2: "",
    //     ps3: "",
    //     ps4: "",
    //   },
    //   newValuesRec: [
    //     {
    //       newValueSel1: "",
    //       newValueSel2: "",
    //       newValueInp1: "",
    //       newValueInp2: "",
    //       newValueInp3: "",
    //       m: "",
    //       S: "",
    //       cost: "",
    //     },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],
    // },
    // triangle: {
    //   newArray: {
    //     type: "",
    //     id: 0,
    //     steel: 0,
    //     param: {
    //       A: 0,
    //       B: 0,
    //       alpha: 0,
    //     },
    //     s: 0,
    //     Q: 0,
    //     m: 0,
    //     summ_m: 0,
    //     S: 0,
    //     summ_S: 0,
    //     P: 0,
    //     cost: 0,
    //     summ: 0,
    //   },
    //   triholders: {},
    //   newValuesTri: [
    //     {
    //       newValueSel1: "",
    //       newValueSel2: "",
    //       newValueInp1: "",
    //       newValueInp2: "",
    //       newValueInp3: "",
    //       newValueInp4: "",
    //       m: "",
    //       S: "",
    //       Cost: "",
    //     },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],
    // },
    // circle: {
    //   newArray: {
    //     type: "",
    //     id: 0,
    //     steel: 0,
    //     param: {
    //       A: 0,
    //       B: 0,
    //       alpha: 0,
    //     },
    //     s: 0,
    //     Q: 0,
    //     m: 0,
    //     summ_m: 0,
    //     S: 0,
    //     summ_S: 0,
    //     P: 0,
    //     cost: 0,
    //     summ: 0,
    //   },
    //   cirholders: {},
    //   newValuesCir: [
    //     {
    //       newValueSel1: "",
    //       newValueSel2: "",
    //       newValueInp1: "",
    //       newValueInp2: "",
    //       m: "",
    //       S: "",
    //       Cost: "",
    //     },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],
    // },
    // washer: {
    //   newArray: {
    //     type: "",
    //     id: 0,
    //     steel: 0,
    //     param: {
    //       A: 0,
    //       B: 0,
    //       alpha: 0,
    //     },
    //     s: 0,
    //     Q: 0,
    //     m: 0,
    //     summ_m: 0,
    //     S: 0,
    //     summ_S: 0,
    //     P: 0,
    //     cost: 0,
    //     summ: 0,
    //   },
    //   washolders: {},
    //   newValuesWas: [
    //     {
    //       newValueSel1: "",
    //       newValueSel2: "",
    //       newValueInp1: "",
    //       newValueInp2: "",
    //       newValueInp3: "",
    //       m: "",
    //       S: "",
    //       Cost: "",
    //     },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],
    // },
    // sector: {
    //   newArray: {
    //     type: "",
    //     id: 0,
    //     steel: 0,
    //     param: {
    //       A: 0,
    //       B: 0,
    //       alpha: 0,
    //     },
    //     s: 0,
    //     Q: 0,
    //     m: 0,
    //     summ_m: 0,
    //     S: 0,
    //     summ_S: 0,
    //     P: 0,
    //     cost: 0,
    //     summ: 0,
    //   },
    //   secholders: {},
    //   newValuesSec: [
    //     {
    //       newValueSel1: "",
    //       newValueSel2: "",
    //       newValueInp1: "",
    //       newValueInp2: "",
    //       newValueInp3: "",
    //       newValueInp4: "",
    //       m: "",
    //       S: "",
    //       Cost: "",
    //     },
    //   ],
    //   thickness: [{ s: 4 }, { s: 5 }, { s: 6 }, { s: 7 }, { s: 8 }],
    // },
    

    // SpecArray: [
    //   {
    //     name: "Наименование",
    //     id: "№п.",
    //     steel: "Материал",
    //     s: "Толщина",
    //     A: 0,
    //     B: 0,
    //     alpha: "Угол",
    //     Q: "Кол-во.",
    //     m: "Вес шт.",
    //     S: "Площадь шт.",
    //     cost: "Цена шт.",
    //     summ: "Стоимость",
    //     summ_m: "всего кг.",
    //     summ_S: "всего площадь",
    //     counter: 0,
    //     email:"",
    //     tel:""
    //   },
    // ],
};

module.exports = state

